version: "3.3"

services:
  mariadbMoodle:

    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'

  moodle:
    image: docker.io/bitnami/moodle:3
    ports:
      - '80:8080'
    environment:
      - MOODLE_DATABASE_HOST=mariadbMoodle
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadbMoodle

  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "Metadev"
      LDAP_DOMAIN: "metadev.ninja"
      LDAP_ADMIN_PASSWORD: "admin"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    domainname: "metadev.ninja"
    hostname: "openldap"
    
  phpldapadminForOpenLDAP:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - '8080:80'
    depends_on:
      - openldap

  nextcloudDB:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud-db
      - MYSQL_USER=nextcloud
    volumes:
      - ./nextcloud-data-db:/var/lib/mysql
   
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud-db
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloudDB
    volumes:
      - ./nextcloud-data/:/var/www/html
    ports:
      - 1234:80
    depends_on:
      - nextcloudDB

  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./config/gitlab:/etc/gitlab
      - ./data/gitlab:/var/opt/gitlab
      - ./logs:/var/log/gitlab


  apache:
    image: php:7.4.1-apache
    container_name: apache
    ports:
      - "8083:80"
    volumes:
      - ./lamp/www:/var/www/html
    links:
      - lampDB:db

  lampDB:
    image: bitnami/mariadb
    environment:
      MARIADB_USER : admin
      MARIADB_PASSWORD : admin
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: apache-db


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - lampDB:db
    ports:
      - "8084:80"


volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
  mariadbApache:
    driver: local
  
